### ISSUE TITLE
Add syntax test files.

### ISSUE THREAD

**Issue by twadleigh** [JuliaEditorSupport/3rd-Party-Highlighters#5]
Would this be the right place to house a collection of source files that can be used to visually test various syntax highlighting schemes?

I'm currently looking at modifying https://gist.github.com/Wilfred/f1aca44c61ed6e1df603 to suit the needs of https://github.com/julia-vscode/julia-vscode and am realizing that all highlighters could benefit from a common set of test cases.

**Comment by oxinabox** [comment]
No, but they would go well in this Org, as a seperate repo
